// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csuaazxqbhoumldnzjxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzdWFhenhxYmhvdW1sZG56anhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNjI4OTEsImV4cCI6MjA1NzczODg5MX0.2pVT1PFlK10Dp5heILk2oHHEL4URzhodlzSuI3zBGFY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);